version: "3.7"

services:
  jenkins:
    # image: jenkins/jenkins:2.346.3-2-lts-jdk17
    build: .
    user: root
    container_name: jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ${HOME}/jenkins_home:/var/jenkins_home
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
